services:
  adguardhome:
    image: adguard/adguardhome:latest
    network_mode: host
    volumes:
      - /var/lib/adguardhome/work:/opt/adguardhome/work
      - /var/lib/adguardhome/conf:/opt/adguardhome/conf
    restart: unless-stopped
